## Import all depedencies

In [3]:
import cv2
import numpy as np
import os
from matplotlib import pyplot as plt
import time
import mediapipe as mp

## Get the key points for face arms and whole body (Basically body pose)

In [7]:
mp_holistic = mp.solutions.holistic
mp_drawing = mp.solutions.drawing_utils #Draw utilities 


In [8]:
def multiple_detection(image,model):
    image = cv2.cvtColor(image,cv2.COLOR_BGR2RGB) #Color convertion 
    image.flags.writeable = False
    results = model.process(image)
    image.flags.writeable = True
    image = cv2.cvtColor(image,cv2.COLOR_RGB2BGR)
    return image,results

In [9]:
def draw_landmarks(image, results):
    mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACEMESH_CONTOURS) # Draw face connections
    mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS) # Draw pose connections
    mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS) # Draw left hand connections
    mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS) # Draw right hand connections

In [10]:
def draw_styled_landmarks(image, results):
    # Draw face connections
    mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACEMESH_CONTOURS, 
                             mp_drawing.DrawingSpec(color=(80,110,10), thickness=1, circle_radius=1), 
                             mp_drawing.DrawingSpec(color=(80,256,121), thickness=1, circle_radius=1)
                             ) 
    # Draw pose connections
    mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS,
                             mp_drawing.DrawingSpec(color=(80,22,10), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(80,44,121), thickness=2, circle_radius=2)
                             ) 
    # Draw left hand connections
    mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                             mp_drawing.DrawingSpec(color=(121,22,76), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(121,44,250), thickness=2, circle_radius=2)
                             ) 
    # Draw right hand connections  
    mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                             mp_drawing.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2)
                             ) 

In [6]:
cap = cv2.VideoCapture("dataset/run/r1.mp4")
with mp_holistic.Holistic(min_detection_confidence=0.6,min_tracking_confidence=0.6) as holistic:
    while cap.isOpened():
    #Read frame
        ret,frame = cap.read()
        if ret == True:
    #Model predictionq
            image,results = multiple_detection(frame,holistic)
            print(results)
        # Draw landmark
            draw_styled_landmarks(image,results)
        # Show screen from user
            cv2.imshow('OpenCv feed',image)
            
            if cv2.waitKey(25) & 0xFF == ord('q'): 
                break
        else:
            break

    cap.release()
    cv2.destroyAllWindows()

<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

In [ ]:
"""cap = cv2.VideoCapture(0)
with mp_holistic.Holistic(min_detection_confidence=0.6,min_tracking_confidence=0.6) as holistic:
    while cap.isOpened():
    #Read frame
        ret,frame = cap.read()
    #Model predictionq
        image,results = multiple_detection(frame,holistic)
        print(results)
    # Draw landmark
        draw_styled_landmarks(image,results)
    # Show screen from user
        cv2.imshow('OpenCv feed',image)

    cap.release()
    cv2.destroyAllWindows()"""

## Extract Keypoints

In [7]:
#len(results.face_landmarks.landmark)

AttributeError: 'NoneType' object has no attribute 'landmark'

In [8]:
len(results.pose_landmarks.landmark)

33

In [9]:
results.pose_landmarks.landmark

[x: 0.05776169
y: 0.3258254
z: 0.068576775
visibility: 0.99862176
, x: 0.057622936
y: 0.31827235
z: 0.04861246
visibility: 0.998301
, x: 0.057030115
y: 0.31813914
z: 0.048568726
visibility: 0.9982736
, x: 0.056372706
y: 0.31808084
z: 0.048516914
visibility: 0.9985827
, x: 0.060183007
y: 0.31819892
z: 0.06753755
visibility: 0.99803174
, x: 0.06146519
y: 0.31801012
z: 0.06752573
visibility: 0.9976224
, x: 0.06284137
y: 0.31786284
z: 0.06747456
visibility: 0.9978628
, x: 0.0580527
y: 0.321122
z: -0.004206581
visibility: 0.9988448
, x: 0.06715263
y: 0.32091424
z: 0.07776397
visibility: 0.9949659
, x: 0.058732733
y: 0.33221644
z: 0.052193996
visibility: 0.9982773
, x: 0.0609718
y: 0.33259717
z: 0.07551953
visibility: 0.99710596
, x: 0.06764039
y: 0.36246708
z: -0.08201587
visibility: 0.9999125
, x: 0.09577838
y: 0.36358178
z: 0.12949269
visibility: 0.9989103
, x: 0.070676886
y: 0.4244881
z: -0.092299305
visibility: 0.9673051
, x: 0.09715904
y: 0.41721523
z: 0.114622526
visibility: 0.1023814

In [10]:
pose = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(132)
face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(1404)
lh = np.array([[res.x, res.y, res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)
rh = np.array([[res.x, res.y, res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)

print (pose.shape, face.shape, lh.shape, rh.shape)
print (pose)

(132,) (1404,) (63,) (63,)
[ 0.05776169  0.32582539  0.06857678  0.99862176  0.05762294  0.31827235
  0.04861246  0.99830103  0.05703012  0.31813914  0.04856873  0.99827361
  0.05637271  0.31808084  0.04851691  0.99858272  0.06018301  0.31819892
  0.06753755  0.99803174  0.06146519  0.31801012  0.06752573  0.99762237
  0.06284137  0.31786284  0.06747456  0.99786282  0.0580527   0.32112199
 -0.00420658  0.9988448   0.06715263  0.32091424  0.07776397  0.99496591
  0.05873273  0.33221644  0.052194    0.99827731  0.0609718   0.33259717
  0.07551953  0.99710596  0.06764039  0.36246708 -0.08201587  0.9999125
  0.09577838  0.36358178  0.12949269  0.99891031  0.07067689  0.4244881
 -0.0922993   0.96730512  0.09715904  0.41721523  0.11462253  0.10238143
  0.04297251  0.42718399 -0.01468361  0.83392781  0.08120701  0.42749718
  0.0439672   0.14350599  0.03738501  0.4304384  -0.02457729  0.77754205
  0.07920477  0.43177345  0.04722922  0.17613104  0.03772345  0.42325541
 -0.01491987  0.77546763  

In [11]:
def extract_keypoints(results):
    pose = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(33*4)
    face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(468*3)
    lh = np.array([[res.x, res.y, res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)
    rh = np.array([[res.x, res.y, res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)
    
    print(pose)

    return np.concatenate([pose, face, lh, rh])

In [12]:
extract_keypoints(results).shape

[ 0.05776169  0.32582539  0.06857678  0.99862176  0.05762294  0.31827235
  0.04861246  0.99830103  0.05703012  0.31813914  0.04856873  0.99827361
  0.05637271  0.31808084  0.04851691  0.99858272  0.06018301  0.31819892
  0.06753755  0.99803174  0.06146519  0.31801012  0.06752573  0.99762237
  0.06284137  0.31786284  0.06747456  0.99786282  0.0580527   0.32112199
 -0.00420658  0.9988448   0.06715263  0.32091424  0.07776397  0.99496591
  0.05873273  0.33221644  0.052194    0.99827731  0.0609718   0.33259717
  0.07551953  0.99710596  0.06764039  0.36246708 -0.08201587  0.9999125
  0.09577838  0.36358178  0.12949269  0.99891031  0.07067689  0.4244881
 -0.0922993   0.96730512  0.09715904  0.41721523  0.11462253  0.10238143
  0.04297251  0.42718399 -0.01468361  0.83392781  0.08120701  0.42749718
  0.0439672   0.14350599  0.03738501  0.4304384  -0.02457729  0.77754205
  0.07920477  0.43177345  0.04722922  0.17613104  0.03772345  0.42325541
 -0.01491987  0.77546763  0.07637095  0.42700016  0.0

(1662,)

## Setup Data path

In [13]:
# Path for exported data, numpy arrays

DATA_PATH = os.path.join(os.getcwd(),'MP_Data') 
# Actions that we try to detect

os.makedirs(os.path.join(DATA_PATH))
# Fourty videos worth of data


In [17]:
no_sequences = 20

# Videos are going to be 40 frames in length
sequence_length = 25

# Folder start
start_folder = 0

In [15]:
actions = np.array(['run', 'walk'])

In [16]:
for action in actions: 
    os.makedirs(os.path.join(DATA_PATH,action))
    
    #dirmax = np.max(np.array(os.listdir(os.path.join(DATA_PATH, action))).astype(int))
    
    for sequence in range(0,no_sequences+1):
        try: 
            os.makedirs(os.path.join(DATA_PATH, action, str(sequence)))
        except:
            pass

In [18]:
DATA_PATH

'c:\\Users\\sahel\\Projects\\Action Recognition\\Skeletal based action recognition\\mediapipe + lstm\\MP_Data'

## Collecting training data

In [20]:
#cap = cv2.VideoCapture(0)
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    
    # NEW LOOP
    # Loop through actions
    for action in actions:
        # Loop through sequences aka videos
        for sequence in range(start_folder, start_folder+no_sequences):
            
            if action == 'run':
                video_path="dataset/"+action+"/r"+str(sequence+1)+".mp4"
            if action == 'walk':
                video_path="dataset/"+action+"/w"+str(sequence+1)+".mp4"
                
            cap = cv2.VideoCapture(video_path)
            # Loop through video length aka sequence length
            for frame_num in range(sequence_length):

                # Read feed
                ret, frame = cap.read()

                # Make detections
                image, results = multiple_detection(frame, holistic)

                # Draw landmarks
                draw_styled_landmarks(image, results)
                
                # NEW Apply wait logi
                cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    # Show to screen
                cv2.imshow('OpenCV Feed', image)
                
                # NEW Export keypoints
                keypoints = extract_keypoints(results)
                npy_path = os.path.join(DATA_PATH, action, str(sequence), str(frame_num))
                np.save(npy_path, keypoints)

                # Break gracefully
                if cv2.waitKey(25) & 0xFF == ord('q'):
                    break
                    
    cap.release()
    cv2.destroyAllWindows()

[ 8.52348387e-01  3.74562889e-01  1.79970562e-02  9.95794892e-01
  8.57193410e-01  3.67480457e-01  1.07437968e-02  9.94398057e-01
  8.58222723e-01  3.67330283e-01  1.06963729e-02  9.93783712e-01
  8.59331489e-01  3.67283940e-01  1.06841996e-02  9.95305836e-01
  8.56630981e-01  3.67509872e-01  2.90412195e-02  9.94816124e-01
  8.57231915e-01  3.67369324e-01  2.90000942e-02  9.94572341e-01
  8.57936203e-01  3.67337257e-01  2.89113540e-02  9.96462047e-01
  8.66723895e-01  3.69244814e-01 -2.09695520e-03  9.93410885e-01
  8.65247607e-01  3.69054794e-01  7.80218318e-02  9.94597077e-01
  8.55543673e-01  3.80735874e-01  1.43484212e-02  9.94984150e-01
  8.54355514e-01  3.81166279e-01  3.75693776e-02  9.94281650e-01
  8.86253297e-01  3.97375584e-01 -6.50026277e-02  9.99818385e-01
  8.69361222e-01  4.11319762e-01  1.41400814e-01  9.98072147e-01
  9.07154322e-01  4.39623386e-01 -1.24286994e-01  9.74992335e-01
  8.74719083e-01  4.63399976e-01  1.61378965e-01  3.18140805e-01
  8.93402636e-01  4.86805

In [19]:
"""cap = cv2.VideoCapture(0)
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    
    # NEW LOOP
    # Loop through actions
    for action in actions:
        # Loop through sequences aka videos
        for sequence in range(start_folder, start_folder+no_sequences):
            # Loop through video length aka sequence length
            for frame_num in range(sequence_length):
                
                # Read feed
                ret, frame = cap.read()
                # Make detections
                image, results = multiple_detection(frame, holistic)
                # Draw landmarks
                draw_styled_landmarks(image, results)
                
                # NEW Export keypoints
                keypoints = extract_keypoints(results)
                npy_path = os.path.join(DATA_PATH, action, str(sequence), str(frame_num))
                np.save(npy_path, keypoints)

                # Break gracefully
                if cv2.waitKey(10) & 0xFF == ord('q'):
                    break
                    
    cap.release()
    cv2.destroyAllWindows()"""

"cap = cv2.VideoCapture(0)\n# Set mediapipe model \nwith mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:\n    \n    # NEW LOOP\n    # Loop through actions\n    for action in actions:\n        # Loop through sequences aka videos\n        for sequence in range(start_folder, start_folder+no_sequences):\n            # Loop through video length aka sequence length\n            for frame_num in range(sequence_length):\n                \n                # Read feed\n                ret, frame = cap.read()\n                # Make detections\n                image, results = multiple_detection(frame, holistic)\n                # Draw landmarks\n                draw_styled_landmarks(image, results)\n                \n                # NEW Export keypoints\n                keypoints = extract_keypoints(results)\n                npy_path = os.path.join(DATA_PATH, action, str(sequence), str(frame_num))\n                np.save(npy_path, keypoints)\n\n   

In [21]:
cap.release()
cv2.destroyAllWindows()

##  Preprocess Data and Create Labels and Features

In [22]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [23]:
label_map = {label:num for num, label in enumerate(actions)}

In [24]:
label_map

{'run': 0, 'walk': 1}

In [25]:
sequences, labels = [], []
for action in actions:
    for sequence in np.array(os.listdir(os.path.join(DATA_PATH, action))).astype(int):
        window = []
        for frame_num in range(sequence_length):
            res = np.load(os.path.join(DATA_PATH, action, str(sequence), "{}.npy".format(frame_num)))
            window.append(res)
        sequences.append(window)
        labels.append(label_map[action])

In [26]:
np.array(sequences).shape

(40, 25, 1662)

In [27]:
np.array(labels).shape

(40,)

In [29]:
sequences

[[array([0.85234839, 0.37456289, 0.01799706, ..., 0.        , 0.        ,
         0.        ]),
  array([0.83723533, 0.37619451, 0.01614341, ..., 0.        , 0.        ,
         0.        ]),
  array([ 0.81605816,  0.3761754 , -0.01913528, ...,  0.        ,
          0.        ,  0.        ]),
  array([ 0.79133528,  0.37439483, -0.00783735, ...,  0.        ,
          0.        ,  0.        ]),
  array([ 0.77217668,  0.36704123, -0.02938283, ...,  0.        ,
          0.        ,  0.        ]),
  array([ 0.75293851,  0.35863316, -0.04822509, ...,  0.        ,
          0.        ,  0.        ]),
  array([ 0.73360902,  0.35412607, -0.05016987, ...,  0.        ,
          0.        ,  0.        ]),
  array([ 0.71167266,  0.35188752, -0.06653936, ...,  0.        ,
          0.        ,  0.        ]),
  array([ 0.68947977,  0.35248637, -0.04381296, ...,  0.        ,
          0.        ,  0.        ]),
  array([ 0.67215365,  0.3550905 , -0.03819352, ...,  0.        ,
          0.       

In [30]:
X = np.array(sequences)

In [32]:
X.shape

(40, 25, 1662)

In [33]:
y = to_categorical(labels).astype(int)

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05)

In [35]:
y_test.shape

(2, 2)

In [36]:
y_test

array([[1, 0],
       [0, 1]])

## Build and Train LSTM Neural Network

In [37]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense,Dropout
from tensorflow.keras.callbacks import TensorBoard
from tensorflow.keras.callbacks import Callback

In [39]:
log_dir = os.path.join(os.getcwd(),'Logs')

os.makedirs(log_dir)
tb_callback = TensorBoard(log_dir=log_dir)

In [40]:
log_dir

'c:\\Users\\sahel\\Projects\\Action Recognition\\Skeletal based action recognition\\mediapipe + lstm\\Logs'

In [41]:
model = Sequential()
model.add(LSTM(64, return_sequences=True, activation='relu', input_shape=(25,1662)))
model.add(LSTM(128, return_sequences=True, activation='relu'))
model.add(LSTM(64, return_sequences=False, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(actions.shape[0], activation='softmax'))

In [42]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['categorical_accuracy','categorical_crossentropy'])

In [43]:
class MyThresholdCallback(Callback):
    def __init__(self, threshold):
        super(MyThresholdCallback, self).__init__()
        self.threshold = threshold

    def on_epoch_end(self, epoch, logs=None): 
        accuracy = logs["categorical_accuracy"]
        if accuracy >= self.threshold:
            self.model.stop_training = True
callback=MyThresholdCallback(threshold=0.95)

In [54]:
%%time
#model.fit(X_train, y_train, epochs=250, callbacks=[callback])
model.fit(X_train, y_train, epochs=250)

Epoch 1/250
2/2 [==============================] - 0s 43ms/step - loss: 0.1475 - categorical_accuracy: 0.8947 - categorical_crossentropy: 0.1475
Epoch 2/250
2/2 [==============================] - 0s 54ms/step - loss: 0.1458 - categorical_accuracy: 0.9211 - categorical_crossentropy: 0.1458
Epoch 3/250
2/2 [==============================] - 0s 45ms/step - loss: 0.1397 - categorical_accuracy: 0.9737 - categorical_crossentropy: 0.1397
Epoch 4/250
2/2 [==============================] - 0s 44ms/step - loss: 0.1636 - categorical_accuracy: 0.9474 - categorical_crossentropy: 0.1636
Epoch 5/250
2/2 [==============================] - 0s 44ms/step - loss: 0.1549 - categorical_accuracy: 0.9474 - categorical_crossentropy: 0.1549
Epoch 6/250
2/2 [==============================] - 0s 46ms/step - loss: 0.1073 - categorical_accuracy: 0.9737 - categorical_crossentropy: 0.1073
Epoch 7/250
2/2 [==============================] - 0s 51ms/step - loss: 0.2172 - categorical_accuracy: 0.8947 - categorical_crosse

In [45]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 25, 64)            442112    
                                                                 
 lstm_1 (LSTM)               (None, 25, 128)           98816     
                                                                 
 lstm_2 (LSTM)               (None, 64)                49408     
                                                                 
 dense (Dense)               (None, 64)                4160      
                                                                 
 dense_1 (Dense)             (None, 32)                2080      
                                                                 
 dense_2 (Dense)             (None, 2)                 66        
                                                                 
Total params: 596642 (2.28 MB)
Trainable params: 596642 

In [62]:
y_train

array([[0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1]])

In [60]:
res = model.predict(X_train)

2/2 [==============================] - 0s 10ms/step


In [64]:
actions[np.argmax(res[3])]

'walk'

## Save Weights

In [65]:
actions[np.argmax(y_test[1])]

'walk'

In [66]:
import h5py
model.save('action.h5')

C:\Users\sahel\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [67]:
del model

In [4]:
from keras import models    
model = models.load_model('action.h5')

## Evaluation of the model

In [69]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score

In [74]:
yhat = model.predict(X_train)

2/2 [==============================] - 0s 10ms/step


In [75]:
ytrue = np.argmax(y_train, axis=1).tolist()
yhat = np.argmax(yhat, axis=1).tolist()

In [76]:
multilabel_confusion_matrix(ytrue, yhat)

array([[[18,  1],
        [ 0, 19]],

       [[19,  0],
        [ 1, 18]]], dtype=int64)

In [77]:
accuracy_score(ytrue, yhat)

0.9736842105263158

## Test in Real Time

In [78]:
# 1. New detection variables
sequence = []
sentence = []
predictions = []
threshold = 0.5

cap = cv2.VideoCapture(0)
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():

        # Read feed
        ret, frame = cap.read()

        # Make detections
        image, results = multiple_detection(frame, holistic)
        print(results)
        
        # Draw landmarks
        draw_styled_landmarks(image, results)
        
        # 2. Prediction logic
        keypoints = extract_keypoints(results)
        sequence.append(keypoints)
        sequence = sequence[-25:]
        
        if len(sequence) == 25:
            res = model.predict(np.expand_dims(sequence, axis=0))[0]
            print(actions[np.argmax(res)])
            
         # Show to screen
        cv2.imshow('OpenCV Feed', image)

        # Break gracefully
        if cv2.waitKey(25) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

<class 'mediapipe.python.solution_base.SolutionOutputs'>
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'mediapipe.python.solution_base.SolutionOutputs'>
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'mediapipe.python.solution_base.SolutionOutputs'>
[0. 0. 0. 0. 0. 0. 0. 0

In [5]:
from scipy import stats

In [6]:
colors = [(245,117,16), (117,245,16), (16,117,245),(200,103,27)]
def prob_viz(res, actions, input_frame, colors):
    output_frame = input_frame.copy()
    for num, prob in enumerate(res):
        cv2.rectangle(output_frame, (0,60+num*40), (int(prob*100), 90+num*40), colors[num], -1)
        cv2.putText(output_frame, actions[num], (0, 85+num*40), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255), 2, cv2.LINE_AA)
        
    return output_frame

In [12]:
# 1. New detection variables
sequence = []
sentence = []
predictions = []
threshold = 0.5

cap = cv2.VideoCapture(0)
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():

        # Read feed
        ret, frame = cap.read()

        # Make detections
        image, results = multiple_detection(frame, holistic)
        print(results)
        
        # Draw landmarks
        draw_styled_landmarks(image, results)
        
        # 2. Prediction logic
        keypoints = extract_keypoints(results)
        sequence.append(keypoints)
        sequence = sequence[-30:]
        
        if len(sequence) == 30:
            res = model.predict(np.expand_dims(sequence, axis=0))[0]
            print(actions[np.argmax(res)])
            predictions.append(np.argmax(res))
            
            
        #3. Viz logic
            if np.unique(predictions[-10:])[0]==np.argmax(res): 
                if res[np.argmax(res)] > threshold: 
                    
                    if len(sentence) > 0: 
                        if actions[np.argmax(res)] != sentence[-1]:
                            sentence.append(actions[np.argmax(res)])
                    else:
                        sentence.append(actions[np.argmax(res)])

            if len(sentence) > 5: 
                sentence = sentence[-5:]

            # Viz probabilities
            image = prob_viz(res, actions, image, colors)
            
        cv2.rectangle(image, (0,0), (640, 40), (245, 117, 16), -1)
        cv2.putText(image, ' '.join(sentence), (3,30), 
                       cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)
        
        # Show to screen
        cv2.imshow('OpenCV Feed', image)

        # Break gracefully
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

<class 'mediapipe.python.solution_base.SolutionOutputs'>
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'mediapipe.python.solution_base.SolutionOutputs'>
[ 5.54424405e-01  4.74878490e-01 -5.63188016e-01  9.99810398e-01
  5.73104560e-01  3.98181796e-01 -5.84685564e-01  9.99561846e-01
  5.91773629e-01  3.92195433e-01 -5.84228992e-01  9.99704182e-01
  6.10377848e-01  3.87423247e-01 -5.84453583e-01  9.99600947e-01
  5.33361554e-01  4.11289692e-01 -5.30799687e-01  9.99465525e-01
  5.26047468e-01  4.13622171e-01 -5.30234873e-01  9.99606669e-01
  5.19062638e-01  4.15884614e-01 -5.30783951e-01  9.99499321e-01
  6.56751275e-01  4.04801637

ValueError: in user code:

    File "C:\Users\sahel\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 2440, in predict_function  *
        return step_function(self, iterator)
    File "C:\Users\sahel\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 2425, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\sahel\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 2413, in run_step  **
        outputs = model.predict_step(data)
    File "C:\Users\sahel\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 2381, in predict_step
        return self(x, training=False)
    File "C:\Users\sahel\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\sahel\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 25, 1662), found shape=(None, 30, 1662)


: 

## Let us try to predict from Video

In [2]:
# 1. New detection variables
sequence = []
sentence = []
predictions = []
threshold = 0.5

cap = cv2.VideoCapture("dataset/run/r1.mp4")
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():

        # Read feed
        ret, frame = cap.read()

        # Make detections
        image, results = multiple_detection(frame, holistic)
        print(results)
        
        # Draw landmarks
        draw_styled_landmarks(image, results)
        
        # 2. Prediction logic
        keypoints = extract_keypoints(results)
        sequence.append(keypoints)
        sequence = sequence[-30:]
        
        if len(sequence) == 30:
            res = model.predict(np.expand_dims(sequence, axis=0))[0]
            print(actions[np.argmax(res)])
            predictions.append(np.argmax(res))
            
            
        #3. Viz logic
            if np.unique(predictions[-10:])[0]==np.argmax(res): 
                if res[np.argmax(res)] > threshold: 
                    
                    if len(sentence) > 0: 
                        if actions[np.argmax(res)] != sentence[-1]:
                            sentence.append(actions[np.argmax(res)])
                    else:
                        sentence.append(actions[np.argmax(res)])

            if len(sentence) > 5: 
                sentence = sentence[-5:]

            # Viz probabilities
            image = prob_viz(res, actions, image, colors)
            
        cv2.rectangle(image, (0,0), (640, 40), (245, 117, 16), -1)
        cv2.putText(image, ' '.join(sentence), (3,30), 
                       cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)
        
        # Show to screen
        cv2.imshow('OpenCV Feed', image)

        # Break gracefully
        if cv2.waitKey(25) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

NameError: name 'cv2' is not defined

In [39]:
cap.release()
cv2.destroyAllWindows()